/**
 * MessageTimeline - Visual chronology of chat messages for debug panel
 */

import { memo } from "react";
import { Badge } from "@/components/ui/badge";
import { cn } from "@/lib/utils";
import { useDebugStore, type DebugMessageSnapshot, type BlockedAction } from "@/stores/debugStore";
import { User, Bot, Settings, ShieldAlert, Clock } from "lucide-react";

function formatTime(ts: number): string {
  return new Date(ts).toLocaleTimeString("fr-FR", {
    hour: "2-digit",
    minute: "2-digit",
    second: "2-digit",
  });
}

function formatRelative(ts: number, prevTs?: number): string | null {
  if (!prevTs) return null;
  const diff = Math.round((ts - prevTs) / 1000);
  if (diff < 1) return "<1s";
  if (diff < 60) return `+${diff}s`;
  return `+${Math.floor(diff / 60)}m${diff % 60}s`;
}

const roleConfig = {
  user: { icon: User, label: "User", color: "bg-blue-500/10 text-blue-600 border-blue-500/30" },
  assistant: { icon: Bot, label: "AI", color: "bg-purple-500/10 text-purple-600 border-purple-500/30" },
  system: { icon: Settings, label: "Sys", color: "bg-gray-500/10 text-gray-500 border-gray-500/30" },
};

function MessageTimelineComponent() {
  const { messageTimeline, blockedActions } = useDebugStore();

  if (messageTimeline.length === 0) {
    return (
      <div className="text-center text-muted-foreground text-sm py-8">
        <Clock className="h-8 w-8 mx-auto mb-2 opacity-50" />
        <p>Aucun message dans la timeline</p>
        <p className="text-xs mt-1">Les messages apparaîtront ici en temps réel</p>
      </div>
    );
  }

  // Merge messages and blocked actions into a single sorted timeline
  const events: Array<
    | { kind: "message"; data: DebugMessageSnapshot; ts: number }
    | { kind: "blocked"; data: BlockedAction; ts: number }
  > = [
    ...messageTimeline.map((m) => ({ kind: "message" as const, data: m, ts: m.timestamp })),
    ...blockedActions.map((a) => ({ kind: "blocked" as const, data: a, ts: a.timestamp })),
  ].sort((a, b) => a.ts - b.ts);

  return (
    <div className="space-y-1">
      {events.map((event, i) => {
        const prevTs = i > 0 ? events[i - 1].ts : undefined;
        const relative = formatRelative(event.ts, prevTs);

        if (event.kind === "blocked") {
          const a = event.data;
          return (
            <div key={`blocked-${a.timestamp}`} className="flex items-start gap-2 px-2 py-1.5 rounded-md bg-red-500/5 border border-red-500/20">
              <ShieldAlert className="h-3.5 w-3.5 text-red-500 mt-0.5 shrink-0" />
              <div className="flex-1 min-w-0">
                <div className="flex items-center gap-1.5">
                  <Badge variant="outline" className="text-[10px] bg-red-500/10 text-red-600 border-red-500/30">
                    BLOCKED
                  </Badge>
                  <span className="text-[10px] text-muted-foreground font-mono">{formatTime(a.timestamp)}</span>
                  {relative && <span className="text-[10px] text-muted-foreground">({relative})</span>}
                </div>
                <p className="text-xs mt-0.5 truncate">
                  chooseWidget → <span className="font-mono">{a.widgetType}</span>: "{a.option}"
                </p>
              </div>
            </div>
          );
        }

        const m = event.data;
        const config = roleConfig[m.role];
        const Icon = config.icon;

        return (
          <div
            key={m.id}
            className={cn(
              "flex items-start gap-2 px-2 py-1.5 rounded-md hover:bg-muted/50 transition-colors",
              m.isAutoGenerated && "opacity-60"
            )}
          >
            <Icon className="h-3.5 w-3.5 mt-0.5 shrink-0 text-muted-foreground" />
            <div className="flex-1 min-w-0">
              <div className="flex items-center gap-1.5 flex-wrap">
                <Badge variant="outline" className={cn("text-[10px]", config.color)}>
                  {config.label}
                </Badge>
                <span className="text-[10px] text-muted-foreground font-mono">{formatTime(m.timestamp)}</span>
                {relative && <span className="text-[10px] text-muted-foreground">({relative})</span>}
                {m.widget && (
                  <Badge variant="outline" className={cn(
                    "text-[10px] font-mono",
                    m.widgetConfirmed
                      ? "bg-green-500/10 text-green-600 border-green-500/30"
                      : "bg-yellow-500/10 text-yellow-600 border-yellow-500/30"
                  )}>
                    {m.widget}{m.widgetConfirmed ? " ✓" : " ⏳"}
                  </Badge>
                )}
                {m.isAutoGenerated && (
                  <Badge variant="outline" className="text-[10px] text-muted-foreground">auto</Badge>
                )}
              </div>
              <p className="text-xs mt-0.5 text-foreground/80 line-clamp-2">{m.textPreview}</p>
            </div>
          </div>
        );
      })}
    </div>
  );
}

export default memo(MessageTimelineComponent);
