/**
 * Date widget handlers - handleDateSelect, handleDateRangeSelect
 */

import { format, addDays, isSameDay } from "date-fns";
import type { ChatMessage } from "../../types";
import type { HandlerDeps } from "./types";
import { parseDurationToDays } from "./helpers";
import { useDebugStore } from "@/stores/debugStore";

/**
 * Handle single date selection
 */
export function handleDateSelect(
  deps: HandlerDeps,
  messageId: string,
  dateType: "departure" | "return",
  date: Date
) {
  const { memory, updateMemory, setMessages, tracking, t, dateFnsLocale, refs } = deps;

  // Bug 9: Track user interaction
  useDebugStore.getState().addUserInteraction({
    timestamp: Date.now(),
    category: "widget",
    action: "confirmed",
    widgetType: "datePicker",
    detail: `${dateType}: ${format(date, "yyyy-MM-dd")}`,
  });

  let nextMem = { ...memory, passengers: { ...memory.passengers } };

  if (dateType === "departure") {
    nextMem = { ...nextMem, departureDate: date };
    updateMemory({ departureDate: date });

    if (refs.pendingTripDuration.current) {
      const days = parseDurationToDays(refs.pendingTripDuration.current);
      if (days) {
        const computedReturn = addDays(date, days);
        nextMem = { ...nextMem, returnDate: computedReturn };
        updateMemory({ returnDate: computedReturn });
      }
      refs.pendingTripDuration.current = null;
    }
  } else {
    nextMem = { ...nextMem, returnDate: date };
    updateMemory({ returnDate: date });
  }

  tracking.trackDateSelect(date, dateType);

  const dateLabel = format(date, "d MMMM yyyy", { locale: dateFnsLocale });
  setMessages((prev) =>
    prev.map((m) =>
      m.id === messageId
        ? { ...m, widgetConfirmed: true, widgetSelectedValue: date, widgetDisplayLabel: dateLabel }
        : m
    )
  );

  const userChoiceMessage: ChatMessage = {
    id: `user-choice-date-${Date.now()}`,
    role: "user",
    text: dateType === "departure"
      ? t("planner.widget.userChoice.departOn", { date: dateLabel })
      : t("planner.widget.userChoice.returnOn", { date: dateLabel }),
    isAutoGenerated: true,
  };
  setMessages((prev) => [...prev, userChoiceMessage]);

  const confirmText =
    dateType === "departure"
      ? t("planner.widget.confirm.date", { date: format(date, "d MMMM yyyy", { locale: dateFnsLocale }) })
      : t("planner.widget.confirm.returnDate", { date: format(date, "d MMMM yyyy", { locale: dateFnsLocale }) });

  if (dateType === "departure" && refs.pendingTravelersWidget.current) {
    refs.pendingTravelersWidget.current = false;

    const computedReturnInfo = nextMem.returnDate
      ? ` ${t("planner.widget.ask.dateWithReturn", { confirm: "", returnDate: format(nextMem.returnDate, "d MMMM", { locale: dateFnsLocale }) }).trim()}`
      : "";

    setMessages((prev) => [
      ...prev,
      {
        id: `confirm-date-${Date.now()}`,
        role: "assistant",
        text: `${confirmText}${computedReturnInfo}`,
        widget: "travelersSelector",
      },
    ]);
  } else {
    setMessages((prev) => [
      ...prev,
      { id: `confirm-date-${Date.now()}`, role: "assistant", text: confirmText },
    ]);
  }

  return nextMem;
}

/**
 * Handle date range selection (both departure AND return)
 */
export function handleDateRangeSelect(
  deps: HandlerDeps,
  messageId: string,
  departure: Date,
  returnDate: Date
) {
  // Bug 6 fix: Prevent same-day departure and return
  if (isSameDay(departure, returnDate)) {
    console.warn("[handleDateRangeSelect] Same day departure and return, ignoring");
    return;
  }

  const { updateMemory, setMessages, tracking, t, dateFnsLocale, refs } = deps;

  // Bug 9: Track user interaction
  useDebugStore.getState().addUserInteraction({
    timestamp: Date.now(),
    category: "widget",
    action: "confirmed",
    widgetType: "dateRangePicker",
    detail: `${format(departure, "yyyy-MM-dd")} → ${format(returnDate, "yyyy-MM-dd")}`,
  });

  updateMemory({ departureDate: departure, returnDate: returnDate });
  refs.pendingTripDuration.current = null;
  refs.pendingPreferredMonth.current = null;

  tracking.trackDateRangeSelect(departure, returnDate);

  const rangeLabel = `${format(departure, "d MMM", { locale: dateFnsLocale })} → ${format(returnDate, "d MMM yyyy", { locale: dateFnsLocale })}`;
  setMessages((prev) =>
    prev.map((m) =>
      m.id === messageId
        ? { ...m, widgetConfirmed: true, widgetSelectedValue: { departure, returnDate }, widgetDisplayLabel: rangeLabel }
        : m
    )
  );

  const userChoiceMessage: ChatMessage = {
    id: `user-choice-dates-${Date.now()}`,
    role: "user",
    text: t("planner.widget.userChoice.dateRange", { from: format(departure, "d MMMM", { locale: dateFnsLocale }), to: format(returnDate, "d MMMM yyyy", { locale: dateFnsLocale }) }),
    isAutoGenerated: true,
  };
  setMessages((prev) => [...prev, userChoiceMessage]);

  const needsTravelersWidget =
    refs.pendingTravelersWidget.current || !refs.travelersConfirmed.current;
  refs.pendingTravelersWidget.current = false;

  if (needsTravelersWidget) {
    setMessages((prev) => [
      ...prev,
      {
        id: `confirm-dates-${Date.now()}`,
        role: "assistant",
        text: t("planner.widget.confirm.dateRangeWithTravelers", { from: format(departure, "d MMMM", { locale: dateFnsLocale }), to: format(returnDate, "d MMMM yyyy", { locale: dateFnsLocale }) }),
        widget: "travelersSelector",
      },
    ]);
  } else {
    setMessages((prev) => [
      ...prev,
      {
        id: `confirm-dates-${Date.now()}`,
        role: "assistant",
        text: t("planner.widget.confirm.datesConfirmed", { from: format(departure, "d MMMM", { locale: dateFnsLocale }), to: format(returnDate, "d MMMM yyyy", { locale: dateFnsLocale }) }),
      },
    ]);
  }
}
