/**
 * Location widget handlers - airport, city, departure city selection
 */

import { format, addDays } from "date-fns";
import { eventBus } from "@/lib/eventBus";
import type { AirportInfo } from "@/stores/hooks";
import type { Airport } from "@/hooks/useNearestAirports";
import type { WidgetType } from "@/types/flight";
import type { ChatMessage } from "../../types";
import type { HandlerDeps } from "./types";
import { parseDurationToDays } from "./helpers";

/**
 * Handle airport selection
 */
export function handleAirportSelect(
  deps: HandlerDeps,
  messageId: string,
  field: "from" | "to",
  airport: Airport,
  isDual?: boolean
) {
  const { memory, updateMemory, setMessages, tracking, t } = deps;

  if (isDual) {
    setMessages((prev) =>
      prev.map((m) => {
        if (m.id !== messageId || !m.dualAirportChoices) return m;
        const updated = { ...m.dualAirportChoices };
        if (field === "from") delete updated.from;
        if (field === "to") delete updated.to;
        const stillHasChoices = updated.from || updated.to;
        return { ...m, dualAirportChoices: stillHasChoices ? updated : undefined };
      })
    );
  } else {
    setMessages((prev) =>
      prev.map((m) =>
        m.id === messageId ? { ...m, airportChoices: undefined } : m
      )
    );
  }

  const existingInfo = field === "from" ? memory.departure : memory.arrival;
  const airportInfo: AirportInfo = {
    airport: airport.name,
    iata: airport.iata,
    city: airport.city_name,
    country: existingInfo?.country,
    countryCode: airport.country_code || existingInfo?.countryCode,
    lat: airport.lat,
    lng: airport.lon,
  };

  if (field === "from") {
    updateMemory({ departure: airportInfo });
  } else {
    updateMemory({ arrival: airportInfo });
  }

  tracking.trackAirportSelect(airport.name, airport.iata, field === "from" ? "departure" : "arrival");

  const confirmText =
    field === "from"
      ? t("planner.widget.confirm.departure", { airport: airport.name })
      : t("planner.widget.confirm.arrival", { airport: airport.name });

  setMessages((prev) => [
    ...prev,
    { id: `confirm-${Date.now()}-${field}`, role: "assistant", text: confirmText },
  ]);

  eventBus.emit("flight:selectAirport", { field, airport: { ...airport, type: "airport" } });
}

/**
 * Handle city selection (destination)
 */
export function handleCitySelect(
  deps: HandlerDeps,
  messageId: string,
  cityName: string,
  countryName: string,
  countryCode: string
) {
  const { memory, updateMemory, setMessages, tracking, t, dateFnsLocale, refs } = deps;

  refs.citySelectionShownForCountry.current = null;
  updateMemory({ arrival: { city: cityName, country: countryName, countryCode } });
  tracking.trackCitySelect(cityName, countryName);

  const cityLabel = `${cityName}, ${countryName}`;

  setMessages((prev) =>
    prev.map((m) =>
      m.id === messageId
        ? { ...m, widgetConfirmed: true, widgetSelectedValue: { cityName, countryName, countryCode }, widgetDisplayLabel: cityLabel }
        : m
    )
  );

  const userChoiceMessage: ChatMessage = {
    id: `user-choice-city-${Date.now()}`,
    role: "user",
    text: t("planner.widget.userChoice.selectCity", { city: cityName, country: countryName }),
    isAutoGenerated: true,
  };
  setMessages((prev) => [...prev, userChoiceMessage]);

  const hasTripDuration = !!refs.pendingTripDuration.current;
  const isOneway = memory.tripType === "oneway";

  if (!memory.departureDate) {
    let widgetType: WidgetType;
    let messageText: string;

    if (hasTripDuration) {
      widgetType = "datePicker";
      messageText = t("planner.widget.ask.cityDurationChoice", { city: cityName, duration: refs.pendingTripDuration.current });
    } else if (isOneway) {
      widgetType = "datePicker";
      messageText = t("planner.widget.ask.cityDepartureChoice", { city: cityName });
    } else {
      widgetType = "dateRangePicker";
      messageText = t("planner.widget.ask.cityDateChoice", { city: cityName });
    }

    setMessages((prev) => [
      ...prev,
      {
        id: `ask-date-after-city-${Date.now()}`,
        role: "assistant",
        text: messageText,
        widget: widgetType,
        widgetData: {
          preferredMonth: refs.pendingPreferredMonth.current || undefined,
          tripDuration: refs.pendingTripDuration.current || undefined,
        },
      },
    ]);
  } else if (!memory.returnDate && memory.tripType !== "oneway") {
    if (hasTripDuration) {
      const days = parseDurationToDays(refs.pendingTripDuration.current!);
      if (days) {
        const computedReturn = addDays(memory.departureDate!, days);
        updateMemory({ returnDate: computedReturn });
        refs.pendingTripDuration.current = null;

        setMessages((prev) => [
          ...prev,
          {
            id: `ask-travelers-after-city-${Date.now()}`,
            role: "assistant",
            text: t("planner.widget.ask.cityDateRange", { city: cityName, from: format(memory.departureDate!, "d MMMM", { locale: dateFnsLocale }), to: format(computedReturn, "d MMMM", { locale: dateFnsLocale }) }),
            widget: "travelersSelector",
          },
        ]);
      }
    } else {
      setMessages((prev) => [
        ...prev,
        {
          id: `ask-return-after-city-${Date.now()}`,
          role: "assistant",
          text: t("planner.widget.ask.returnDateChoice"),
          widget: "returnDatePicker",
          widgetData: { preferredMonth: refs.pendingPreferredMonth.current || undefined },
        },
      ]);
    }
  } else if (memory.passengers.adults < 1) {
    setMessages((prev) => [
      ...prev,
      {
        id: `ask-travelers-after-city-${Date.now()}`,
        role: "assistant",
        text: t("planner.widget.ask.cityTravelers", { city: cityName }),
        widget: "travelersSelector",
      },
    ]);
  }
}

/**
 * Handle departure city selection
 */
export function handleDepartureCitySelect(
  deps: HandlerDeps,
  messageId: string,
  cityName: string,
  countryName: string,
  countryCode: string
) {
  const { memory, updateMemory, setMessages, tracking, t, refs } = deps;

  updateMemory({ departure: { city: cityName, country: countryName, countryCode } });
  refs.pendingFromCountry.current = null;
  tracking.trackCitySelect(cityName, `${countryName} (départ)`);

  const cityLabel = `${cityName}, ${countryName}`;

  setMessages((prev) =>
    prev.map((m) =>
      m.id === messageId
        ? { ...m, widgetConfirmed: true, widgetSelectedValue: { cityName, countryName, countryCode }, widgetDisplayLabel: cityLabel }
        : m
    )
  );

  const userChoiceMessage: ChatMessage = {
    id: `user-choice-departure-${Date.now()}`,
    role: "user",
    text: t("planner.widget.userChoice.departFrom", { city: cityName }),
    isAutoGenerated: true,
  };
  setMessages((prev) => [...prev, userChoiceMessage]);

  if (!memory.arrival?.city) {
    setMessages((prev) => [
      ...prev,
      {
        id: `ask-destination-${Date.now()}`,
        role: "assistant",
        text: t("planner.widget.confirm.departureCity", { city: cityName }),
      },
    ]);
  }
}
