/**
 * Traveler widget handlers
 */

import { eventBus } from "@/lib/eventBus";
import type { ChatMessage } from "../../types";
import type { HandlerDeps } from "./types";

/**
 * Handle travelers selection
 */
export function handleTravelersSelect(
  deps: HandlerDeps,
  messageId: string,
  travelers: { adults: number; children: number; infants: number }
) {
  const { updateMemory, updateTravelers, setMessages, tracking, t, buildTravelersLabel, refs } = deps;

  updateMemory({ passengers: travelers });
  refs.travelersConfirmed.current = true;

  updateTravelers({
    adults: travelers.adults,
    children: travelers.children,
    infants: travelers.infants,
    childrenAges: [],
  });

  tracking.trackTravelersSelect(travelers);

  const travelersLabel = buildTravelersLabel(travelers);

  setMessages((prev) =>
    prev.map((m) =>
      m.id === messageId
        ? { ...m, widgetConfirmed: true, widgetSelectedValue: travelers, widgetDisplayLabel: travelersLabel }
        : m
    )
  );

  const userChoiceMessage: ChatMessage = {
    id: `user-choice-travelers-${Date.now()}`,
    role: "user",
    text: t("planner.widget.userChoice.travelers", { label: travelersLabel }),
    isAutoGenerated: true,
  };
  setMessages((prev) => [...prev, userChoiceMessage]);

  setMessages((prev) => [
    ...prev,
    {
      id: `confirm-travelers-${Date.now()}`,
      role: "assistant",
      text: t("planner.widget.confirm.travelersWithTripType", { label: travelersLabel }),
      widget: "tripTypeConfirm",
    },
  ]);
}

/**
 * Handle solo travel confirmation
 */
export function handleTravelersConfirmSolo(
  deps: HandlerDeps,
  messageId: string
) {
  const { setMessages, tracking, refs } = deps;

  tracking.trackTravelersSelect({ adults: 1, children: 0, infants: 0 });

  setMessages((prev) =>
    prev.map((m) =>
      m.id === messageId ? { ...m, widget: undefined } : m
    )
  );
  refs.pendingSearchAfterTravelers.current = false;
  eventBus.emit("flight:triggerSearch");
}

/**
 * Handle travelers edit before search
 */
export function handleTravelersEditBeforeSearch(
  deps: HandlerDeps,
  messageId: string,
  travelers: { adults: number; children: number; infants: number }
) {
  const { updateMemory, setMessages, tracking, t, buildTravelersLabel, refs } = deps;

  updateMemory({ passengers: travelers });
  tracking.trackTravelersSelect(travelers);

  setMessages((prev) =>
    prev.map((m) =>
      m.id === messageId ? { ...m, widget: undefined } : m
    )
  );
  refs.pendingSearchAfterTravelers.current = false;

  const travelersLabel = buildTravelersLabel(travelers);

  setMessages((prev) => [
    ...prev,
    {
      id: `search-ready-updated-${Date.now()}`,
      role: "assistant",
      text: t("planner.widget.confirm.searchReadyUpdated", { label: travelersLabel }),
      hasSearchButton: true,
    },
  ]);
}
