/**
 * Trip type confirmation handler
 */

import type { ChatMessage } from "../../types";
import type { HandlerDeps } from "./types";

/**
 * Handle trip type confirmation
 */
export function handleTripTypeConfirm(
  deps: HandlerDeps,
  messageId: string,
  tripType: "roundtrip" | "oneway" | "multi"
) {
  const { updateMemory, setMessages, tracking, t, refs } = deps;

  updateMemory({ tripType });
  tracking.trackTripTypeSelect(tripType);

  const tripTypeKey = { roundtrip: "roundtrip", oneway: "oneway", multi: "multi" }[tripType];
  const tripTypeLabel = t(`planner.widget.tripType.${tripTypeKey}`);

  setMessages((prev) =>
    prev.map((m) =>
      m.id === messageId
        ? { ...m, widgetConfirmed: true, widgetSelectedValue: tripType, widgetDisplayLabel: tripTypeLabel }
        : m
    )
  );

  const userChoiceMessage: ChatMessage = {
    id: `user-choice-triptype-${Date.now()}`,
    role: "user",
    text: tripType === "roundtrip"
      ? t("planner.widget.userChoice.roundtrip")
      : tripType === "oneway"
        ? t("planner.widget.userChoice.oneway")
        : t("planner.widget.userChoice.multi"),
    isAutoGenerated: true,
  };
  setMessages((prev) => [...prev, userChoiceMessage]);

  if (tripType === "multi") {
    setMessages((prev) => [
      ...prev,
      { id: `ask-multi-${Date.now()}`, role: "assistant", text: t("planner.widget.ask.multiSteps") },
    ]);
  } else {
    refs.searchButtonShown.current = true;
    setMessages((prev) => [
      ...prev,
      {
        id: `search-ready-${Date.now()}`,
        role: "assistant",
        text: t("planner.widget.confirm.tripType", { type: tripTypeLabel }),
        hasSearchButton: true,
      },
    ]);
  }
}
