/**
 * sessionHelpers - Pure utility functions for chat session management.
 *
 * Extracted from useChatSessions to keep the hook focused on React state.
 * Contains types, title/preview generation, emoji mapping, and smart title API.
 */

import i18n from "@/i18n/config";
import { SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY } from "@/integrations/supabase/client";

// ─── Types ───

export interface StoredMessage {
  id: string;
  role: "assistant" | "user" | "system";
  text: string;
  timestamp?: number;
  hasSearchButton?: boolean;
  isHidden?: boolean;
  isStreaming?: boolean;
  isTyping?: boolean;
  widget?: string;
  widgetData?: unknown;
  widgetConfirmed?: boolean;
  widgetSelectedValue?: unknown;
  widgetDisplayLabel?: string;
  isAutoGenerated?: boolean;
}

export interface ChatSession {
  id: string;
  title: string;
  createdAt: number;
  updatedAt: number;
  preview: string;
  titleGenerated?: boolean;
}

export interface ChatTranslations {
  newConversation: string;
  startConversation: string;
  welcomeMessage: string;
}

// ─── Helpers ───

export const generateId = () => crypto.randomUUID();

export const getTranslations = (): ChatTranslations => ({
  newConversation: i18n.t("planner.chat.newConversation"),
  startConversation: i18n.t("planner.chat.startConversation"),
  welcomeMessage: i18n.t("planner.chat.welcomeMessage"),
});

export const getDefaultWelcomeMessage = (
  translations = getTranslations(),
): StoredMessage => ({
  id: "welcome",
  role: "assistant",
  text: translations.welcomeMessage,
});

// ─── Emoji mapping for trip titles ───

const TRIP_EMOJIS: Record<string, string> = {
  plage: "\u{1F3D6}\uFE0F", beach: "\u{1F3D6}\uFE0F", mer: "\u{1F30A}", ocean: "\u{1F30A}",
  montagne: "\u26F0\uFE0F", mountain: "\u26F0\uFE0F", ski: "\u26F7\uFE0F", neige: "\u2744\uFE0F",
  ville: "\u{1F3D9}\uFE0F", city: "\u{1F3D9}\uFE0F", urban: "\u{1F306}",
  nature: "\u{1F33F}", foret: "\u{1F332}", forest: "\u{1F332}",
  desert: "\u{1F3DC}\uFE0F", safari: "\u{1F981}",
  asie: "\u{1F3EF}", asia: "\u{1F3EF}", japon: "\u{1F5FC}", japan: "\u{1F5FC}", tokyo: "\u{1F5FC}", chine: "\u{1F409}", china: "\u{1F409}",
  europe: "\u{1F3F0}", paris: "\u{1F5FC}", france: "\u{1F1EB}\u{1F1F7}", italie: "\u{1F1EE}\u{1F1F9}", italy: "\u{1F35D}", rome: "\u{1F3DB}\uFE0F", espagne: "\u{1F1EA}\u{1F1F8}", spain: "\u{1F483}",
  amerique: "\u{1F5FD}", america: "\u{1F5FD}", usa: "\u{1F1FA}\u{1F1F8}", newyork: "\u{1F5FD}", miami: "\u{1F334}", losangeles: "\u{1F3AC}",
  afrique: "\u{1F30D}", africa: "\u{1F30D}", maroc: "\u{1F54C}", morocco: "\u{1F54C}", egypte: "\u{1F3FA}", egypt: "\u{1F3FA}",
  ile: "\u{1F3DD}\uFE0F", island: "\u{1F3DD}\uFE0F", maldives: "\u{1F3DD}\uFE0F", bali: "\u{1F33A}", hawaii: "\u{1F33A}",
  romantique: "\u{1F495}", romantic: "\u{1F495}", honeymoon: "\u{1F492}",
  aventure: "\u{1F9D7}", adventure: "\u{1F9D7}", randonnee: "\u{1F97E}", hiking: "\u{1F97E}",
  famille: "\u{1F468}\u200D\u{1F469}\u200D\u{1F467}\u200D\u{1F466}", family: "\u{1F468}\u200D\u{1F469}\u200D\u{1F467}\u200D\u{1F466}", enfants: "\u{1F476}", kids: "\u{1F476}",
  solo: "\u{1F392}", backpack: "\u{1F392}",
  luxe: "\u2728", luxury: "\u2728", spa: "\u{1F486}",
  gastronomie: "\u{1F37D}\uFE0F", food: "\u{1F35C}", cuisine: "\u{1F468}\u200D\u{1F373}",
  weekend: "\u{1F31F}", vacances: "\u{1F334}", holidays: "\u{1F334}", voyage: "\u2708\uFE0F", trip: "\u2708\uFE0F",
};

export const getEmojiForText = (text: string): string => {
  const lowerText = text.toLowerCase();
  for (const [keyword, emoji] of Object.entries(TRIP_EMOJIS)) {
    if (lowerText.includes(keyword)) {
      return emoji;
    }
  }
  return "\u2708\uFE0F";
};

// ─── Title & preview generation ───

export const generateSimpleTitle = (
  messages: StoredMessage[],
  translations = getTranslations(),
): string => {
  const firstUserMessage = messages.find((m) => m.role === "user");
  if (firstUserMessage) {
    const text = firstUserMessage.text.slice(0, 35);
    const emoji = getEmojiForText(firstUserMessage.text);
    const truncatedText =
      text.length < firstUserMessage.text.length ? text + "..." : text;
    return `${emoji} ${truncatedText}`;
  }
  return `\u2708\uFE0F ${translations.newConversation}`;
};

export const countUserMessages = (messages: StoredMessage[]): number => {
  return messages.filter((m) => m.role === "user" && !m.isHidden).length;
};

export const generateSmartTitle = async (
  messages: StoredMessage[],
): Promise<{ title: string; emoji: string } | null> => {
  try {
    const response = await fetch(
      `${SUPABASE_URL}/functions/v1/generate-chat-title`,
      {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          apikey: SUPABASE_PUBLISHABLE_KEY,
        },
        body: JSON.stringify({
          messages: messages
            .map((m) => ({ role: m.role, content: m.text }))
            .slice(-6),
        }),
      },
    );

    if (!response.ok) {
      console.error(
        "[ChatSessions] Smart title generation failed:",
        response.status,
      );
      return null;
    }

    const data = await response.json();
    return { title: data.title, emoji: data.emoji };
  } catch (error) {
    console.error("[ChatSessions] Smart title generation error:", error);
    return null;
  }
};

export const generatePreview = (
  messages: StoredMessage[],
  translations = getTranslations(),
): string => {
  const lastMessage = [...messages]
    .reverse()
    .find((m) => !m.isHidden && m.text);
  if (lastMessage) {
    const text = lastMessage.text.slice(0, 50);
    return text.length < lastMessage.text.length ? text + "..." : text;
  }
  return translations.startConversation;
};
