
-- Add ~170 more destination aliases (FR cities, FR countries, FR regions, ES, DE)
INSERT INTO public.destination_aliases (alias, canonical_name, lang) VALUES
  -- FR cities
  ('Le Caire', 'Cairo', 'fr'),
  ('Athènes', 'Athens', 'fr'),
  ('Athenes', 'Athens', 'fr'),
  ('Copenhague', 'Copenhagen', 'fr'),
  ('Édimbourg', 'Edinburgh', 'fr'),
  ('Edimbourg', 'Edinburgh', 'fr'),
  ('Genève', 'Geneva', 'fr'),
  ('Geneve', 'Geneva', 'fr'),
  ('Varsovie', 'Warsaw', 'fr'),
  ('Bucarest', 'Bucharest', 'fr'),
  ('Moscou', 'Moscow', 'fr'),
  ('Pékin', 'Beijing', 'fr'),
  ('Pekin', 'Beijing', 'fr'),
  ('Séoul', 'Seoul', 'fr'),
  ('Hanoï', 'Hanoi', 'fr'),
  ('Manille', 'Manila', 'fr'),
  ('La Havane', 'Havana', 'fr'),
  ('Bogotá', 'Bogota', 'fr'),
  ('Casablanca', 'Casablanca', 'fr'),
  ('Marrakech', 'Marrakech', 'fr'),
  ('Fès', 'Fez', 'fr'),
  ('Fes', 'Fez', 'fr'),
  ('Alger', 'Algiers', 'fr'),
  ('Venise', 'Venice', 'fr'),
  ('Florence', 'Florence', 'fr'),
  ('Naples', 'Naples', 'fr'),
  ('Séville', 'Seville', 'fr'),
  ('Seville', 'Seville', 'fr'),
  ('Majorque', 'Mallorca', 'fr'),
  ('Minorque', 'Menorca', 'fr'),
  ('Corfou', 'Corfu', 'fr'),
  ('Crète', 'Crete', 'fr'),
  ('Crete', 'Crete', 'fr'),
  ('Santorin', 'Santorini', 'fr'),

  -- FR countries (missing from initial batch)
  ('Algérie', 'Algeria', 'fr'),
  ('Algerie', 'Algeria', 'fr'),
  ('Birmanie', 'Myanmar', 'fr'),
  ('Sri Lanka', 'Sri Lanka', 'fr'),
  ('Laos', 'Laos', 'fr'),
  ('Népal', 'Nepal', 'fr'),
  ('Nepal', 'Nepal', 'fr'),
  ('Irlande', 'Ireland', 'fr'),
  ('Écosse', 'Scotland', 'fr'),
  ('Ecosse', 'Scotland', 'fr'),
  ('Danemark', 'Denmark', 'fr'),
  ('Finlande', 'Finland', 'fr'),
  ('Pologne', 'Poland', 'fr'),
  ('Hongrie', 'Hungary', 'fr'),
  ('Roumanie', 'Romania', 'fr'),
  ('Bulgarie', 'Bulgaria', 'fr'),
  ('Serbie', 'Serbia', 'fr'),
  ('Albanie', 'Albania', 'fr'),
  ('Lituanie', 'Lithuania', 'fr'),
  ('Lettonie', 'Latvia', 'fr'),
  ('Estonie', 'Estonia', 'fr'),
  ('Slovénie', 'Slovenia', 'fr'),
  ('Slovenie', 'Slovenia', 'fr'),
  ('Slovaquie', 'Slovakia', 'fr'),
  ('Tchéquie', 'Czechia', 'fr'),
  ('Tchequie', 'Czechia', 'fr'),
  ('Russie', 'Russia', 'fr'),
  ('Géorgie', 'Georgia', 'fr'),
  ('Georgie', 'Georgia', 'fr'),
  ('Arménie', 'Armenia', 'fr'),
  ('Armenie', 'Armenia', 'fr'),
  ('Oman', 'Oman', 'fr'),
  ('Qatar', 'Qatar', 'fr'),
  ('Liban', 'Lebanon', 'fr'),
  ('Kenya', 'Kenya', 'fr'),
  ('Ouganda', 'Uganda', 'fr'),
  ('Rwanda', 'Rwanda', 'fr'),
  ('Éthiopie', 'Ethiopia', 'fr'),
  ('Ethiopie', 'Ethiopia', 'fr'),
  ('Cameroun', 'Cameroon', 'fr'),
  ('Madagascar', 'Madagascar', 'fr'),
  ('Namibie', 'Namibia', 'fr'),
  ('Botswana', 'Botswana', 'fr'),
  ('Cuba', 'Cuba', 'fr'),
  ('Jamaïque', 'Jamaica', 'fr'),
  ('Jamaique', 'Jamaica', 'fr'),
  ('Panama', 'Panama', 'fr'),
  ('Équateur', 'Ecuador', 'fr'),
  ('Equateur', 'Ecuador', 'fr'),
  ('Bolivie', 'Bolivia', 'fr'),
  ('Uruguay', 'Uruguay', 'fr'),
  ('Chili', 'Chile', 'fr'),
  ('Australie', 'Australia', 'fr'),
  ('Fidji', 'Fiji', 'fr'),
  ('Tahiti', 'Tahiti', 'fr'),
  ('Polynésie', 'French Polynesia', 'fr'),
  ('Polynesie', 'French Polynesia', 'fr'),
  ('Réunion', 'Reunion', 'fr'),
  ('Reunion', 'Reunion', 'fr'),
  ('Martinique', 'Martinique', 'fr'),
  ('Guadeloupe', 'Guadeloupe', 'fr'),

  -- FR regions/islands
  ('Sardaigne', 'Sardinia', 'fr'),
  ('Sicile', 'Sicily', 'fr'),
  ('Canaries', 'Canary Islands', 'fr'),
  ('Baléares', 'Balearic Islands', 'fr'),
  ('Baleares', 'Balearic Islands', 'fr'),
  ('Açores', 'Azores', 'fr'),
  ('Acores', 'Azores', 'fr'),

  -- ES common aliases
  ('Japón', 'Japan', 'es'),
  ('Tailandia', 'Thailand', 'es'),
  ('Alemania', 'Germany', 'es'),
  ('Francia', 'France', 'es'),
  ('Grecia', 'Greece', 'es'),
  ('Turquía', 'Turkey', 'es'),
  ('Marruecos', 'Morocco', 'es'),
  ('Egipto', 'Egypt', 'es'),
  ('Brasil', 'Brazil', 'es'),
  ('Perú', 'Peru', 'es'),
  ('México', 'Mexico', 'es'),
  ('Estados Unidos', 'United States', 'es'),
  ('Reino Unido', 'United Kingdom', 'es'),
  ('Países Bajos', 'Netherlands', 'es'),
  ('Suiza', 'Switzerland', 'es'),
  ('Noruega', 'Norway', 'es'),
  ('Suecia', 'Sweden', 'es'),
  ('Dinamarca', 'Denmark', 'es'),
  ('Islandia', 'Iceland', 'es'),
  ('Croacia', 'Croatia', 'es'),
  ('Hungría', 'Hungary', 'es'),
  ('Polonia', 'Poland', 'es'),
  ('Rumania', 'Romania', 'es'),
  ('Londres', 'London', 'es'),
  ('Atenas', 'Athens', 'es'),

  -- DE common aliases
  ('Frankreich', 'France', 'de'),
  ('Spanien', 'Spain', 'de'),
  ('Italien', 'Italy', 'de'),
  ('Griechenland', 'Greece', 'de'),
  ('Ägypten', 'Egypt', 'de'),
  ('Türkei', 'Turkey', 'de'),
  ('Marokko', 'Morocco', 'de'),
  ('Brasilien', 'Brazil', 'de'),
  ('Mexiko', 'Mexico', 'de'),
  ('Niederlande', 'Netherlands', 'de'),
  ('Schweiz', 'Switzerland', 'de'),
  ('Norwegen', 'Norway', 'de'),
  ('Schweden', 'Sweden', 'de'),
  ('Dänemark', 'Denmark', 'de'),
  ('Kroatien', 'Croatia', 'de'),
  ('Ungarn', 'Hungary', 'de'),
  ('Polen', 'Poland', 'de'),
  ('Rumänien', 'Romania', 'de'),
  ('Tschechien', 'Czechia', 'de'),
  ('Österreich', 'Austria', 'de'),
  ('Indien', 'India', 'de'),
  ('Südkorea', 'South Korea', 'de'),
  ('Neuseeland', 'New Zealand', 'de'),
  ('Südafrika', 'South Africa', 'de'),
  ('Australien', 'Australia', 'de')
ON CONFLICT (alias, lang) DO NOTHING;
