
-- Add popular tourist destinations that fall below the 112k population cutoff
-- These are famous travel destinations that users frequently mention
INSERT INTO public.destination_aliases (alias, canonical_name, lang) VALUES
  -- Self-referencing aliases for destinations not in the top-5000 cities
  ('Bali', 'Bali', 'fr'),
  ('Bali', 'Bali', 'en'),
  ('Ibiza', 'Ibiza', 'fr'),
  ('Ibiza', 'Ibiza', 'en'),
  ('Mykonos', 'Mykonos', 'fr'),
  ('Mykonos', 'Mykonos', 'en'),
  ('Santorini', 'Santorini', 'fr'),
  ('Santorini', 'Santorini', 'en'),
  ('Santorin', 'Santorini', 'fr'),
  ('Bora Bora', 'Bora Bora', 'fr'),
  ('Bora Bora', 'Bora Bora', 'en'),
  ('Bora-Bora', 'Bora Bora', 'fr'),
  ('Bora-Bora', 'Bora Bora', 'en'),
  ('Zanzibar', 'Zanzibar', 'fr'),
  ('Zanzibar', 'Zanzibar', 'en'),
  ('Phuket', 'Phuket', 'fr'),
  ('Phuket', 'Phuket', 'en'),
  ('Cancun', 'Cancun', 'fr'),
  ('Cancún', 'Cancun', 'fr'),
  ('Cancun', 'Cancun', 'en'),
  ('Tulum', 'Tulum', 'fr'),
  ('Tulum', 'Tulum', 'en'),
  ('Marbella', 'Marbella', 'fr'),
  ('Marbella', 'Marbella', 'en'),
  ('Malaga', 'Malaga', 'fr'),
  ('Malaga', 'Malaga', 'en'),
  ('Málaga', 'Malaga', 'es'),
  ('Dubrovnik', 'Dubrovnik', 'fr'),
  ('Dubrovnik', 'Dubrovnik', 'en'),
  ('Hvar', 'Hvar', 'fr'),
  ('Hvar', 'Hvar', 'en'),
  ('Cinque Terre', 'Cinque Terre', 'fr'),
  ('Cinque Terre', 'Cinque Terre', 'en'),
  ('Amalfi', 'Amalfi', 'fr'),
  ('Amalfi', 'Amalfi', 'en'),
  ('Capri', 'Capri', 'fr'),
  ('Capri', 'Capri', 'en'),
  ('Positano', 'Positano', 'fr'),
  ('Positano', 'Positano', 'en'),
  ('Maui', 'Maui', 'fr'),
  ('Maui', 'Maui', 'en'),
  ('Honolulu', 'Honolulu', 'en'),
  ('Ko Samui', 'Ko Samui', 'fr'),
  ('Ko Samui', 'Ko Samui', 'en'),
  ('Koh Samui', 'Ko Samui', 'fr'),
  ('Koh Samui', 'Ko Samui', 'en'),
  ('Koh Phi Phi', 'Koh Phi Phi', 'fr'),
  ('Koh Phi Phi', 'Koh Phi Phi', 'en'),
  ('Langkawi', 'Langkawi', 'fr'),
  ('Langkawi', 'Langkawi', 'en'),
  ('Lombok', 'Lombok', 'fr'),
  ('Lombok', 'Lombok', 'en'),
  ('Nusa Dua', 'Nusa Dua', 'fr'),
  ('Nusa Dua', 'Nusa Dua', 'en'),
  ('Ubud', 'Ubud', 'fr'),
  ('Ubud', 'Ubud', 'en'),
  ('Seminyak', 'Seminyak', 'fr'),
  ('Seminyak', 'Seminyak', 'en'),
  ('Canggu', 'Canggu', 'fr'),
  ('Canggu', 'Canggu', 'en'),
  ('Siem Reap', 'Siem Reap', 'fr'),
  ('Siem Reap', 'Siem Reap', 'en'),
  ('Luang Prabang', 'Luang Prabang', 'fr'),
  ('Luang Prabang', 'Luang Prabang', 'en'),
  ('Kyoto', 'Kyoto', 'fr'),
  ('Kyoto', 'Kyoto', 'en'),
  ('Petra', 'Petra', 'fr'),
  ('Petra', 'Petra', 'en'),
  ('Marrakesh', 'Marrakech', 'en'),
  ('Essaouira', 'Essaouira', 'fr'),
  ('Essaouira', 'Essaouira', 'en'),
  ('Chefchaouen', 'Chefchaouen', 'fr'),
  ('Chefchaouen', 'Chefchaouen', 'en'),
  ('Havana', 'Havana', 'en'),
  ('Varadero', 'Varadero', 'fr'),
  ('Varadero', 'Varadero', 'en'),
  ('Playa del Carmen', 'Playa del Carmen', 'fr'),
  ('Playa del Carmen', 'Playa del Carmen', 'en'),
  ('Cartagena', 'Cartagena', 'fr'),
  ('Cartagena', 'Cartagena', 'en'),
  ('Carthagène', 'Cartagena', 'fr'),
  ('Machu Picchu', 'Machu Picchu', 'fr'),
  ('Machu Picchu', 'Machu Picchu', 'en'),
  ('Cusco', 'Cusco', 'fr'),
  ('Cusco', 'Cusco', 'en'),
  ('Cuzco', 'Cusco', 'fr'),
  ('Patagonie', 'Patagonia', 'fr'),
  ('Patagonia', 'Patagonia', 'en'),
  ('Galapagos', 'Galapagos', 'fr'),
  ('Galápagos', 'Galapagos', 'fr'),
  ('Galapagos', 'Galapagos', 'en'),
  ('Cap-Vert', 'Cape Verde', 'fr'),
  ('Cape Verde', 'Cape Verde', 'en'),
  ('Djerba', 'Djerba', 'fr'),
  ('Djerba', 'Djerba', 'en'),
  ('Hurghada', 'Hurghada', 'fr'),
  ('Hurghada', 'Hurghada', 'en'),
  ('Sharm el-Sheikh', 'Sharm el-Sheikh', 'fr'),
  ('Sharm el-Sheikh', 'Sharm el-Sheikh', 'en'),
  ('Charm el-Cheikh', 'Sharm el-Sheikh', 'fr'),
  ('Antalya', 'Antalya', 'fr'),
  ('Antalya', 'Antalya', 'en'),
  ('Bodrum', 'Bodrum', 'fr'),
  ('Bodrum', 'Bodrum', 'en'),
  ('Fethiye', 'Fethiye', 'fr'),
  ('Fethiye', 'Fethiye', 'en'),
  ('Cappadoce', 'Cappadocia', 'fr'),
  ('Cappadocia', 'Cappadocia', 'en'),
  ('Queenstown', 'Queenstown', 'fr'),
  ('Queenstown', 'Queenstown', 'en'),
  ('Rotorua', 'Rotorua', 'fr'),
  ('Rotorua', 'Rotorua', 'en'),
  ('Gold Coast', 'Gold Coast', 'en'),
  ('Cairns', 'Cairns', 'en'),
  ('Whitsundays', 'Whitsundays', 'en'),
  ('Moorea', 'Moorea', 'fr'),
  ('Moorea', 'Moorea', 'en'),
  ('Rangiroa', 'Rangiroa', 'fr'),
  ('Rangiroa', 'Rangiroa', 'en'),
  ('Reykjavik', 'Reykjavik', 'fr'),
  ('Reykjavik', 'Reykjavik', 'en'),
  ('Tromsø', 'Tromso', 'fr'),
  ('Tromso', 'Tromso', 'en'),
  ('Bergen', 'Bergen', 'fr'),
  ('Bergen', 'Bergen', 'en'),
  ('Lofoten', 'Lofoten', 'fr'),
  ('Lofoten', 'Lofoten', 'en'),
  ('Laponie', 'Lapland', 'fr'),
  ('Lapland', 'Lapland', 'en'),
  ('Rovaniemi', 'Rovaniemi', 'fr'),
  ('Rovaniemi', 'Rovaniemi', 'en'),
  ('Tallinn', 'Tallinn', 'fr'),
  ('Tallinn', 'Tallinn', 'en'),
  ('Riga', 'Riga', 'fr'),
  ('Riga', 'Riga', 'en'),
  ('Vilnius', 'Vilnius', 'fr'),
  ('Vilnius', 'Vilnius', 'en'),
  ('Split', 'Split', 'fr'),
  ('Split', 'Split', 'en'),
  ('Kotor', 'Kotor', 'fr'),
  ('Kotor', 'Kotor', 'en'),
  ('Sorrente', 'Sorrento', 'fr'),
  ('Sorrento', 'Sorrento', 'en'),
  ('Côte Amalfitaine', 'Amalfi Coast', 'fr'),
  ('Amalfi Coast', 'Amalfi Coast', 'en')
ON CONFLICT (alias, lang) DO NOTHING;
